blueprint:
  name: Xiaomi Mi wireless remote switch WXKG01LM (MQTT Device Trigger)
  description: |
    This blueprint enables automation for the Xiaomi Mi WXKG01LM switch using MQTT device triggers.
    It supports different press types: single, double, triple, quadruple, many presses, hold, and release.
  domain: automation
  input:
    mode:
      name: Automation Modes
      description: https://www.home-assistant.io/docs/automation/modes/
      default: parallel
      selector:
        select:
          mode: dropdown
          options:
            - single
            - restart
            - queued
            - parallel
    zigbee_device:
      name: Zigbee Device - Xiaomi Mi WXKG01LM
      description: Select the correct Zigbee device to use.
      selector:
        device:
          integration: mqtt
    single:
      name: Single button press
      description: Action to run
      default: []
      selector:
        action: {}
    double:
      name: Double button press
      description: Action to run
      default: []
      selector:
        action: {}
    triple:
      name: Triple button press
      description: Action to run
      default: []
      selector:
        action: {}
    quadruple:
      name: Quadruple button press
      description: Action to run
      default: []
      selector:
        action: {}
    many:
      name: Many button press
      description: Action to run
      default: []
      selector:
        action: {}
    hold:
      name: Hold of button
      description: Action to run
      default: []
      selector:
        action: {}
    release:
      name: Release of button
      description: Action to run
      default: []
      selector:
        action: {}
mode: !input mode
max_exceeded: silent
trigger:
  - platform: device
    device_id: !input zigbee_device
    domain: mqtt
    type: action
    subtype: single
    id: single
  - platform: device
    device_id: !input zigbee_device
    domain: mqtt
    type: action
    subtype: double
    id: double
  - platform: device
    device_id: !input zigbee_device
    domain: mqtt
    type: action
    subtype: triple
    id: triple
  - platform: device
    device_id: !input zigbee_device
    domain: mqtt
    type: action
    subtype: quadruple
    id: quadruple
  - platform: device
    device_id: !input zigbee_device
    domain: mqtt
    type: action
    subtype: many
    id: many
  - platform: device
    device_id: !input zigbee_device
    domain: mqtt
    type: action
    subtype: hold
    id: hold
  - platform: device
    device_id: !input zigbee_device
    domain: mqtt
    type: action
    subtype: release
    id: release
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: single
        sequence: !input single
      - conditions:
          - condition: trigger
            id: double
        sequence: !input double
      - conditions:
          - condition: trigger
            id: triple
        sequence: !input triple
      - conditions:
          - condition: trigger
            id: quadruple
        sequence: !input quadruple
      - conditions:
          - condition: trigger
            id: many
        sequence: !input many
      - conditions:
          - condition: trigger
            id: hold
        sequence: !input hold
      - conditions:
          - condition: trigger
            id: release
        sequence: !input release
